server:
  port: 8090

management:
  security:
    enabled: false

spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
      path: /h2-console;
  datasource:
    url: jdbc:h2:file:~/test;DB_CLOSE_DELAY=-1;
    username: sa
    password:
    driver-class-name: org.h2.Driver

management:
  endpoints:
    web:
      exposure:
        include: mappings,beans


